//@url = "http://127.0.0.1:3333/api/v1"
//@token = "jwt_token"

GET {{url}}/
###

GET {{url}}/user/obtem
Authorization: Bearer {{token}}
###
POST {{url}}/user/create
content-type: application/json

{
    "nome": "Usuário teste",
    "email": "teste2-hero@gmail.com",
    "senha": "123ad123"
}
###

POST  {{url}}/login
content-type: application/json

{
    "email": "teste2-hero@gmail.com",
    "senha": "123ad123"
}
###

GET  {{url}}/pet/classe
content-type: application/json
###

POST  {{url}}/pet/classe
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome" : "Aves",
    "descricao" : ""
}
###