//@url = "http://127.0.0.1:3333/api/v1"
//@token = "jwt_token"

GET {{url}}/
content-type: application/json
###

// user/

GET {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{url}}/user/obtem
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{url}}/user/obtem/5fbfa7f1ee400d001706c4b1
content-type: application/json
Authorization: Bearer {{token}}
###

POST {{url}}/user/create
content-type: application/json

{
    "nome": "Usuário teste",
    "email": "teste2-hero@gmail.com",
    "senha": "123ad123"
}
###

PUT {{url}}/user/update/5fbfa6b6ee400d001706c4b0
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Administrador - Sys"
}
###

// login/ adm
POST  {{url}}/login
content-type: application/json

{
    "email": "{{adm_user}}",
    "senha": "{{adm_pass}}"
}
###

// pet/
GET  {{url}}/pet/classe
content-type: application/json
Authorization: Bearer {{token}}
###

POST  {{url}}/pet/classe
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome" : "Aves",
    "descricao" : ""
}
###